name: 🐛 不具合とか
description: 不具合があるときの報告
labels: ["⚠️bug?"]

body:
  - type: markdown
    attributes:
      value: |
        misskey.dream内で不具合があったらこれで報告してね。

  - type: textarea
    attributes:
      label: 💡 どんな不具合？
      description: バグの概要を教えてね
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🥰 期待する動作
      description: 正常な動作はこれっぽい！っていうのを教えてね
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🤬 現状の動作
      description: |
        現状発生してる異常な動作を教えてね
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📝 再現手順
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    attributes:
      label: 💻 端末情報
      description: |
        不具合が起きたときに使用した環境をできるだけ詳しく教えてね。

        例:
          * OSとデバイス: MacBook Pro (14inch, 2021), macOS Ventura 13.4
          * 使用したブラウザー(バージョンを含めて): Chrome 113.0.5672.126
      value: |
        * OSとデバイス:
        * 使用したブラウザー(バージョンを含めて):
      render: markdown
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Do you want to address this bug yourself?
      options:
        - label: Yes, I will patch the bug myself and send a pull request
