name: ✨ 新規機能とかこうしたいな―っていうもの
description: なんかこうしたいな―っていうのを伝える
labels: ["✨Feature"]

body:
  - type: textarea
    attributes:
      label: 概要
      description: こうしたいな―っていう詳細を聞かせてね
    validations:
      required: true
