---
name: Dockle

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  DOCKER_IMAGE_TAG: 'misskeydream-web'

jobs:
  dockle:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTENT_TRUST: 1
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          curl -L -o dockle.deb "https://github.com/goodwithtech/dockle/releases/download/v0.4.10/dockle_0.4.10_Linux-64bit.deb"
          sudo dpkg -i dockle.deb
      - run: |
          cp .config/docker_example.env .config/docker.env
          cp ./docker-compose_example.yml ./docker-compose.yml
      - run: |
          docker compose up -d web
          docker tag "$(docker compose images web | awk 'OFS=":" {print $4}' | tail -n +2)" ${{ env.DOCKER_IMAGE_TAG }}:latest
      - uses: erzz/dockle-action@v1
        with:
          image: ${{ env.DOCKER_IMAGE_TAG }}
          exit-code: 1
